# To run: conda env create -f environment.yml
# freely change the pytorch, cudatoolkit version, as you preferred.
# only works with tqdm==4.40.0 for now.
name: multi-mono-sf
channels:
    - pytorch
    - conda-forge
    - defaults
dependencies:
    - python=3.8
    - cudatoolkit-dev=11.3
    - pytorch=1.8.1
    - torchvision=0.9.1
    - pip
    - pip:
          - opencv-python
          - colorama
          - scikit-image
          - cupy-cuda11x
          - pytz
          - tqdm==4.40.0
          - tensorboard
          - matplotlib
