# To run: conda env create -f environment.yml
# freely change the pytorch, cudatoolkit version, as you preferred.
# only works with tqdm==4.40.0 for now.
name: multi-mono-sf
channels:
    - pytorch
    - conda-forge
    - defaults
dependencies:
    - python=3.8
    - cudatoolkit=11.3
    - pocl
    - pip
    - pip:
          - torch==1.8.1
          - torchvision==0.9.1
          - opencv-python
          - colorama
          - scikit-image
          - cupy-cuda11x
          - pytz
          - tqdm==4.40.0
          - tensorboard
          - matplotlib
